version: '3.3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbdatabase
    volumes:
      - ./volumen:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
